[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python genesis_songbook/manage.py collectstatic --noinput"

[deploy]
startCommand = "python genesis_songbook/manage.py migrate && gunicorn --chdir genesis_songbook genesis_songbook.wsgi"
restartPolicyType = "on_failure"
