# Generated by Django 6.0.1 on 2026-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_clothing",
            field=models.BooleanField(
                default=False, help_text="Check if this product requires size selection"
            ),
        ),
    ]
