# Generated by Django 6.0.1 on 2026-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("venue", models.CharField(max_length=200)),
                (
                    "location",
                    models.CharField(
                        help_text="City, Country or State", max_length=200
                    ),
                ),
                (
                    "ticket_link",
                    models.URLField(
                        blank=True, help_text="Link to buy tickets", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional show information", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
