# Generated by Django 6.0.1 on 2026-03-08 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_slug",
                    models.SlugField(
                        help_text="URL slug for this page (e.g., 'bio', 'shows', 'videos')",
                        unique=True,
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        help_text="Custom title for this page (60 chars max)",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        help_text="Custom meta description (160 chars max)",
                        max_length=160,
                        validators=[django.core.validators.MaxLengthValidator(160)],
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Additional keywords specific to this page",
                    ),
                ),
                (
                    "og_image",
                    models.URLField(
                        blank=True, help_text="Custom Open Graph image for this page"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page SEO",
                "verbose_name_plural": "Page SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Genesis Songbook",
                        help_text="Your band/site name",
                        max_length=100,
                    ),
                ),
                (
                    "default_title",
                    models.CharField(
                        default="Genesis Songbook - Phil Collins Era Genesis Tribute Band",
                        help_text="Default page title (60 chars max)",
                        max_length=60,
                    ),
                ),
                (
                    "default_description",
                    models.TextField(
                        default="The ultimate Phil Collins fronted Genesis tribute band. Experience the magic of 80s Genesis with authentic performances of your favorite hits.",
                        help_text="Default meta description (160 chars max)",
                        max_length=160,
                        validators=[django.core.validators.MaxLengthValidator(160)],
                    ),
                ),
                (
                    "default_keywords",
                    models.TextField(
                        default="Genesis tribute band, Phil Collins tribute, 80s music, progressive rock, cover band, tribute show",
                        help_text="Comma-separated keywords",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Your primary location (e.g., 'London', 'New York')",
                        max_length=100,
                    ),
                ),
                (
                    "og_image",
                    models.URLField(
                        blank=True,
                        help_text="Default Open Graph image URL (1200x630px recommended)",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                (
                    "twitter_handle",
                    models.CharField(blank=True, help_text="Without @", max_length=50),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "website_url",
                    models.URLField(
                        default="https://your-domain.com",
                        help_text="Your full website URL",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="GA4 Measurement ID (e.g., G-XXXXXXXXXX)",
                        max_length=20,
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console verification code",
                        max_length=100,
                    ),
                ),
                (
                    "band_founded_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Year the tribute band was founded",
                        null=True,
                    ),
                ),
                (
                    "band_genre",
                    models.CharField(
                        default="Progressive Rock, Pop Rock, Art Rock",
                        help_text="Music genres (comma-separated)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
            },
        ),
    ]
