# Generated by Django 6.0.1 on 2026-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_pageseo_seosettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="maps_link",
            field=models.URLField(
                blank=True, help_text="Google Maps link for venue", null=True
            ),
        ),
    ]
