# Generated by Django 6.0.1 on 2026-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_show_maps_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="apple_maps_link",
            field=models.URLField(
                blank=True, help_text="Apple Maps link for venue", null=True
            ),
        ),
    ]
